// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("metadata")
	ScopeName = "go.opentelemetry.io/collector/exporter/metadataexporter"
)

const (
	TracesStability = component.StabilityLevelAlpha
)
